# Generated by Django 4.1.1 on 2022-11-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pol', '0003_product_p1_product_p2_product_p3_product_p4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pol.subcategory'),
        ),
    ]
